app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', [
    'as' => 'home', 'uses' => 'HomeController@index'
]);
Route::get('home/data', [
    'as' => 'home.data', 'uses' => 'HomeController@data'
]);
//CMS
Route::get('login', 'Auth\AuthController@getLogin');
Route::post('login', 'Auth\AuthController@postLogin');
Route::get('logout', 'Auth\AuthController@getLogout');
Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
// Registration routes...
Route::get('register', 'Auth\AuthController@getRegister');
Route::post('register', 'Auth\AuthController@postRegister')->name('auth.register');

Route::get('/', [
    'middleware' => 'auth',
    'uses' => 'AdminController@index'
]);
Route::get('order', [
    'uses' => 'OrderController@index',
    'as' => 'order.index'
]);

Route::resource('category','CategoryController', ['except' => ['show']]);
 Route::resource('sub-category','SubCategoryController', ['except' => ['show']]);
  Route::resource('product','ProductController', ['except' => ['show']]);

});
Route::get('categories/{id}', [
    'uses' => 'Home\CategoryController@show',
    'as' => 'home.category.show'
]);
Route::get('products/{id}', [
    'uses' => 'Home\ProductController@show',
    'as' => 'home.product.show'
]);
Route::get('detail/{id}', [
    'uses' => 'Home\DetailController@show',
    'as' => 'home.detail.show'
]);

Route::post('buy', [
    'uses' => 'Home\CheckoutController@storeSession',
    'as' => 'home.checkout.storeSession'
]);

Route::get('checkout', [
    'uses' => 'Home\CheckoutController@index',
    'as' => 'home.checkout.index'
]);

Route::get('checkout/delete/{id}', [
    'uses' => 'Home\CheckoutController@deleteCart',
    'as' => 'home.checkout.deleteCart'
]);

Route::get('order', [
    'uses' => 'Home\OrderController@order',
    'as' => 'home.order.index'
]);

Route::post('order', [
    'uses' => 'Home\OrderController@store',
    'as' => 'home.order.store'
]);

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    /**
     * Table name
     *
     * @var string
     */
    protected $table = 'products';
    
    protected $fillable = ['slug', 'name', 'title', 'about', 'price', 'img', 'sub_category_id'];
    
    public function category()
    {
        return $this->belongsTo('App\Category','category_id');
    }
    public function getAboutAttribute($value)
    {
        return html_entity_decode($value);
    }

}

app/Http/Controllers/Home/ProductController.php
<?php

namespace App\Http\Controllers\Home;

use App\Http\Controllers\Controller;
use App\Product;

class ProductController extends Controller
{

    public $product;
    
    public function __construct(Product $product)
    {
        $this->product = $product;
    }
    
    public function show($id)
    {
        $products = $this->product->where('sub_category_id',$id)->paginate(10);
        return view('products',['products' => $products]);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Product;
use App\SubCategory;
use App\Http\Requests\ProductRequest;

class ProductController extends Controller
{

    public function create()
    {
        $category = SubCategory::lists('name','id');
        return view('product.create',['cate' => $category]);
    }

    public function store(ProductRequest $request)
    {
        $request->merge([
            'slug' => str_slug($request->get('name'))
        ]);
        $data = $request->all();
        
        $destinationPath = '/img'; // upload path
        $nameImg =\Carbon\Carbon::now()->timestamp.'_'.$request->file('file')->getClientOriginalName();
        $request->file('file')->move(public_path().$destinationPath,$nameImg);
        $data['img'] = 'img/'.$nameImg;
        Product::create($data);
        return redirect()->route('admin.product.index');
    }

    public function index()
    {
        
        $products = Product::orderBy('id', 'desc')->paginate(10);
        return view('product.index', ['products' => $products]);
    }
}

resources/views/product/create.blade.php
@extends('layouts.master')
@section('content')
<h2>PRODUCT</h2>
<div class="form-inner">
        {!! Former::open_for_files()->route('admin.product.store')->method('POST')->files('true') !!}
    <div class="row">
        {!! Former::text('name')
        ->label('Name product')
        ->addGroupClass('col-md-6')
        ->addClass('form-group')
        !!}
    </div>
    <div class="row">
        {!! Former::text('title')
        ->label('Title')
        ->addGroupClass('col-md-6')
        ->addClass('form-group')
        !!}
    </div>
    <div class="row">
        {!! Former::textarea('about')
        ->label('About')
        ->addGroupClass('col-md-6')
        ->addClass('form-group')
        !!}
    </div>
    <div class="row">
        {!! Former::number('price')
        ->label('Price')
        ->addGroupClass('col-md-6')
        ->addClass('form-group')
        !!}
    </div>
    <div class="row">
        {!! Former::file('file')
        ->label('File Image')
        ->addGroupClass('col-md-6')
        ->addClass('form-group')
        ->accept('image') 
        !!}
    </div>
    <div class="row">
    {!! Former::select('sub_category_id')
    ->label('Sub Category')
    ->addClass('form-group')
    ->addGroupClass('col-md-6')
    ->addOption('' ,'')
    ->options($cate)
    !!}
    </div>
</div>
{!! Former::actions()
->primary_submit('create')
!!}
{!! Former::close()!!}
</div>
@stop
@section('js')
<script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
<script src="/vendor/unisharp/laravel-ckeditor/adapters/jquery.js"></script>
<script>
  $('textarea').ckeditor({
    filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
    filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token={{csrf_token()}}',
    filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
    filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token={{csrf_token()}}'
  });
</script>
@stop

resources/views/product/edit.blade.php
<?php
/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

resources/views/product/index.blade.php
@extends('layouts.master')
@section('content')
<div class="container">
    <div class="row">
       <a type="button" class="btn btn-primary" href="{!! route('admin.product.create') !!}">Primary</a>
    </div>
</div>
<div class="container">   
    <div class="row">
    <table class="table table-bordered">
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Title</th>
            <th>About</th>
            <th>Price</th>
            <th>Img</th>
        </tr>
        @foreach ($products as $product)
        <tr>
            <td>{{ $product->id }}</td>
            <td>{{ $product->name }}</td>
            <td>{{ $product->title }}</td>
            <td>{{ $product->about }}</td>
            <td>{{ $product->price }}</td>
            <td><img src="{{asset($product->img)}}" alt="Smiley face" height="42" width="42"></td>
            
        </tr>
        @endforeach
    </table>
    </div>
    <ul class="pagination">
        {!! $products->render() !!}
    </ul>
    </div>
@stop