app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', [
    'as' => 'home', 'uses' => 'HomeController@index'
]);
Route::get('home/data', [
    'as' => 'home.data', 'uses' => 'HomeController@data'
]);
//CMS
Route::get('login', 'Auth\AuthController@getLogin');
Route::post('login', 'Auth\AuthController@postLogin');
Route::get('logout', 'Auth\AuthController@getLogout');
Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
// Registration routes...
Route::get('register', 'Auth\AuthController@getRegister');
Route::post('register', 'Auth\AuthController@postRegister')->name('auth.register');

Route::get('/', [
    'middleware' => 'auth',
    'uses' => 'AdminController@index'
]);
Route::get('order', [
    'uses' => 'OrderController@index',
    'as' => 'order.index'
]);

Route::resource('category','CategoryController', ['except' => ['show']]);
 Route::resource('sub-category','SubCategoryController', ['except' => ['show']]);
  Route::resource('product','ProductController', ['except' => ['show']]);

});
Route::get('categories/{id}', [
    'uses' => 'Home\CategoryController@show',
    'as' => 'home.category.show'
]);
Route::get('products/{id}', [
    'uses' => 'Home\ProductController@show',
    'as' => 'home.product.show'
]);
Route::get('detail/{id}', [
    'uses' => 'Home\DetailController@show',
    'as' => 'home.detail.show'
]);

Route::post('buy', [
    'uses' => 'Home\CheckoutController@storeSession',
    'as' => 'home.checkout.storeSession'
]);

Route::get('checkout', [
    'uses' => 'Home\CheckoutController@index',
    'as' => 'home.checkout.index'
]);

Route::get('checkout/delete/{id}', [
    'uses' => 'Home\CheckoutController@deleteCart',
    'as' => 'home.checkout.deleteCart'
]);

Route::get('order', [
    'uses' => 'Home\OrderController@order',
    'as' => 'home.order.index'
]);

Route::post('order', [
    'uses' => 'Home\OrderController@store',
    'as' => 'home.order.store'
]);

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{

    /**
     * Table name
     *
     * @var string
     */
    protected $table = 'categories';
    
    protected $fillable = ['name'];
    
    public function subCategories()
    {
        return $this->hasMany(SubCategory::class);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Requests\CategoryRequest;
use App\Category;

class CategoryController extends Controller
{

    public function create()
    {
        return view('category.create');
    }

    public function store(CategoryRequest $request)
    {
        Category::create($request->all());
        return redirect()->route('category.index');
    }
    
    public function update(CategoryRequest $request, $id)
    {
        Category::find($id)->update($request->all());
        return redirect()->route('category.index');
    }
    
    public function edit($id)
    {
        
        $category = Category::find($id);
        return view('category.edit',['cat' => $category]);
    }
    public function index()
    {
        $categories = Category::orderBy('id', 'desc')->paginate(10);
        return view('category.index', ['categories' => $categories]);
    }
    
    public function show($id)
    {
        
    }
    public function destroy($id)
    {
        Category::find($id)->delete();
        return redirect()->back();
    }
}

app/Http/Controllers/Home/CategoryController.php
<?php

namespace App\Http\Controllers\Home;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Requests\CategoryRequest;
use App\Category;

class CategoryController extends Controller
{

    public function show($id)
    {
        $categories = Category::orderBy('id', 'desc')->paginate(10);
        return view('category.index', ['categories' => $categories]);
    }
}

resources/views/category/create.blade.php
@extends('layouts.master')
@section('content')
<h2>CATEGORY</h2>
<div class="form-inner">
    {!! Former::open()->route('admin.category.store')->method('POST') !!}

        {!! Former::text('name')
        ->label('Name category')
        ->addGroupClass('col-md-6')
        ->addClass('form-group')
        !!}
    </div>
    {!! Former::actions()
    ->primary_submit('create')
    !!}
    {!! Former::close()!!}
</div>
@stop

resources/views/category/edit.blade.php
@extends('layouts.master')
@section('content')
<h2>CATEGORY</h2>
<div class="form-inner">
    {!! Former::populate($cat) !!}
    {!! Former::open()->route('admin.category.update',$cat->id)->method('PUT') !!}

        {!! Former::text('name')
        ->label('Name category')
        ->addGroupClass('col-md-6')
        ->addClass('form-group')
        !!}
    </div>
    {!! Former::actions()
    ->primary_submit('create')
    !!}
    {!! Former::close()!!}
</div>
@stop

resources/views/category/index.blade.php
@extends('layouts.master')
@section('content')
<div class="container">
    <div class="row">
       <a type="button" class="btn btn-primary" href="{!! route('admin.category.create') !!}">Create Category</a>
    </div>
</div>
<div class="container">   
    <div class="row">
    <table class="table table-hover">
        <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        </thead>
        <tbody>
        @foreach ($categories as $category)
        <tr>
            <td>{{ $category->id }}</td>
            <td>{{ $category->name }}</td>
            <td>
                <a type="button" class="btn btn-info" href="{!! route('admin.category.edit',$category->id) !!}">Edit</a>
            </td>
            <td>
                {!! Former::open('')->route('admin.category.destroy',$category->id)->method('DELETE')!!}
                {!! Former::actions()
                    ->danger_submit('Delete')
                !!}
                {!! Former::close()!!}
            </td>
        </tr>
        @endforeach
        </tbody>
    </table>
    </div>
    <ul class="pagination">
        {!! $categories->render() !!}
    </ul>
    </div>
@stop